; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
; https://docs.platformio.org/page/envvars.html

[platformio]
#core_dir = .pio/core # install tools/framework/platform locally, could be handled by env:PLATFORMIO_CORE_DIR too
build_cache_dir = .pio/build/cache
src_dir = esp32_marauder

[common]
framework = arduino
platform = espressif32
board = lolin_d32
board_build.flash_size = 4MB
board_build.partitions = min_spiffs.csv
build_flags = -w -Wl,-zmuldefs # '-w' disables warning messages
debug_build_flags = -Os -ggdb -w -Wl,-zmuldefs
extra_scripts = pre:libraries/target-setup.py # handles target compiler define and User_Setup.h
lib_deps =
    ivanseidel/LinkedList
    bblanchon/ArduinoJson@6.21.4
    adafruit/Adafruit MAX1704X@1.0.3
    https://github.com/adafruit/Adafruit_NeoPixel@1.15.2
    stevemarple/MicroNMEA@2.0.6
    mathieucarbou/ESPAsyncWebServer@3.1.5
    plerup/EspSoftwareSerial@8.1.0
    marian-craciunescu/ESP32Ping@1.7.0

[common_ble]
extends = common
lib_deps =
    # platformio doesn't merge, so the following library list replaces the base list from [common] section
    ivanseidel/LinkedList
    bblanchon/ArduinoJson@6.21.4
    h2zero/NimBLE-Arduino@1.3.8
    adafruit/Adafruit MAX1704X@1.0.3
    https://github.com/adafruit/Adafruit_NeoPixel@1.15.2
    stevemarple/MicroNMEA@2.0.6
    mathieucarbou/ESPAsyncWebServer@3.1.5
    plerup/EspSoftwareSerial@8.1.0
    marian-craciunescu/ESP32Ping@1.7.0

[common_display]
extends = common
lib_deps =
    # platformio doesn't merge, so the following library list replaces the base list from [common] section
    ivanseidel/LinkedList
    bblanchon/ArduinoJson@6.21.4
    adafruit/Adafruit MAX1704X@1.0.3
    https://github.com/adafruit/Adafruit_NeoPixel@1.15.2
    stevemarple/MicroNMEA@2.0.6
    mathieucarbou/ESPAsyncWebServer@3.1.5
    plerup/EspSoftwareSerial@8.1.0
    marian-craciunescu/ESP32Ping@1.7.0
    Bodmer/TFT_eSPI@2.5.43
    lvgl/lv_arduino@3.0.1
    https://github.com/PaulStoffregen/XPT2046_Touchscreen@1.4.0 #PaulStoffregen/XPT2046_Touchscreen

[common_ble_display]
extends = common_ble
lib_deps =
    # platformio doesn't merge, so the following library list replaces the base list from [common_ble] section
    ivanseidel/LinkedList
    bblanchon/ArduinoJson@6.21.4
    h2zero/NimBLE-Arduino@1.3.8
    adafruit/Adafruit MAX1704X@1.0.3
    https://github.com/adafruit/Adafruit_NeoPixel@1.15.2
    stevemarple/MicroNMEA@2.0.6
    mathieucarbou/ESPAsyncWebServer@3.1.5
    #https://github.com/mathieucarbou/ESPAsyncWebServer/archive/refs/tags/v2.10.4.zip
    #ESP32Async/AsyncTCP@3.4.9 #ESP32Async/ESPAsyncWebServer@3.8.1 #https://github.com/mathieucarbou/ESPAsyncWebServer/archive/refs/tags/v2.10.4.zip
    plerup/EspSoftwareSerial@8.1.0
    marian-craciunescu/ESP32Ping@1.7.0
    Bodmer/TFT_eSPI@2.5.43
    lvgl/lv_arduino@3.0.1
    https://github.com/PaulStoffregen/XPT2046_Touchscreen@1.4.0 #PaulStoffregen/XPT2046_Touchscreen
    #https://github.com/thingpulse/XPT2046_Touchscreen@1.4

[env:Flipper-Zero_WiFi-DevBoard]
extends = common
board = lolin_s2_mini

[env:Flipper-Zero_MultiBoard_S3]
extends = common_ble
board = lolin_s3

[env:OG-Marauder]
extends = common_ble_display

[env:Marauder_v6]
extends = common_ble_display

[env:Marauder_v6_1]
extends = common_ble_display

[env:Marauder-Kit]
extends = common_ble_display

[env:Marauder-Mini]
extends = common_ble_display

[env:ESP32-LDDB]
extends = common_ble

[env:Marauder-DevBoard-Pro]
extends = common_ble

[env:M5StickCPlus]
extends = common_ble_display
board = m5stick-c

[env:M5StickCPlus-2]
extends = common_ble_display
board = m5stick-c

[env:Rev-Feather]
extends = common_display
board = lolin_s2_mini

[env:Marauder_v7]
extends = common_ble_display

[env:Marauder_CYD_2432S028]
extends = common_ble_display

[env:Marauder_CYD_2432S024_GUITION]
extends = common_ble_display

[env:Marauder_CYD_2432S028_2USB]
extends = common_ble_display

[env:Marauder_CYD_3_5inch]
extends = common_ble_display

[env:Marauder_v7_1]
extends = common_ble_display
board = dfrobot_firebeetle2_esp32e
board_build.flash_size = 16MB
board_build.partitions = default_16MB.csv

[env:M5Cardputer]
extends = common_ble_display
board = dfrobot_firebeetle2_esp32s3
board_build.flash_size = 8MB
board_build.partitions = default_8MB.csv

#[env:ESP32-C5_DevKitC-1]
#extends = common_ble
#board = esp32-c5-devkitc-1
